### PR TITLE
Add models

### PR DESCRIPTION
**Pull request by filipecabaco**
1.  `docker run -p 5432:5432 -d postgres`
2. `mix ecto.create`
3. `mix ecto.migrate`

### CODE REVIEW

**Review by seekandystroy — APPROVED** [review]
The code itself looks fine (but I'm really an elixir n00b and never used Ecto).

Can you give me a quick rundown on why are we dividing the API into paragraphs and services?

**Comment by filipecabaco** [comment]
- `services` are the top domain that will then contain a list paragraphs
- `paragraphs` will contain the votes associated with each paragraph and the actual content (html code?)

**Comment by filipecabaco** [comment]
ok to merge?

**Comment by lamuria** [comment]
Do it!

**Pull request merged**
